pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.8-alpine3.16'
                }
            }
            steps {
                sh 'python3.8 -m py_compile CI_CD_pipeline-calculatrice-Jenkins/prog.py CI_CD_pipeline-calculatrice-Jenkins/calc.py'
                sh 'pwd'
                stash(name: 'compiled-results', includes: 'CI_CD_pipeline-calculatrice-Jenkins/*.py*')
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'grihabor/pytest:alpine'
                }
            }
            steps {
                sh 'pytest -v --junit-xml CI_CD_pipeline-calculatrice-Jenkins/test-reports/results.xml CI_CD_pipeline-calculatrice-Jenkins/test_calc.py'
            }
            post {
                always {
                    junit "CI_CD_pipeline-calculatrice-Jenkins/test-reports/results.xml"            
                }
            }
        }
        stage('Deliver') {
            agent any
            environment {
                VOLUME = '$(pwd)/CI_CD_pipeline-calculatrice-Jenkins:/src'
                IMAGE = 'cdrx/pyinstaller-linux'
            }
            steps {
                dir(path: env.BUILD_ID) {
                    unstash(name: 'compiled-results')
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} 'pyinstaller -F CI_CD_pipeline-calculatrice-Jenkins/prog.py'"
                }
            }
            post {
                success {
                    archiveArtifacts "${env.BUILD_ID}/CI_CD_pipeline-calculatrice-Jenkins/dist/prog"
                }
            }
        }
    }
}
