pipeline {
    agent none
    stages {
        stage('Build') {
            agent { aws-agent1 }
            //{
                //docker {
                //    image 'python:3.8-alpine3.16'
                // }
               // aws-agent1
           // }
            steps {
                //sh 'python3.8 -m py_compile sources/prog.py sources/calc.py'
                sh 'python3 --version'
                //stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
    }
}
